url: https://damianzaremba.co.uk
permalink: /:year/:month/:title/
host: 127.0.0.1
port: 4039

lsi: false
show_drafts: false
future: false

exclude: ["README.md", "get_tags.py", ".git", ".gitignore", ".gitkeep"]
source: content
paginate: 5
paginate_path: ":num"

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-paginate

graphviz:
  options: "-Tsvg"

tag_dir: tag
tag_title_prefix: Archive for
tag_meta_description_prefix: Damian Zaremba's Blog Archive For

sitemap:
  exclude:
    - "/feed.xml"
