permalink: /:year/:month/:title/
port: 4039

markdown: rdiscount
pygments: true
lsi: true

exclude: ["README.md", "get_tags.py", ".git", ".svn"]
source: content
paginate: 5

excerpt_separator:

tag_dir: tag
tag_title_prefix: Archive for
tag_meta_description_prefix: Damian Zaremba's Blog Archive For 
