permalink: /:year/:month/:title/
host: 127.0.0.1
port: 4039

markdown: rdiscount
pygments: true
lsi: true

exclude: ["README.md", "get_tags.py", ".git", ".gitignore", ".gitkeep"]
source: content
paginate: 5

excerpt_separator:

tag_dir: tag
tag_title_prefix: Archive for
tag_meta_description_prefix: Damian Zaremba's Blog Archive For 

sitemap:
    exclude:
        - "/feed.xml"
        - "/cf-pages/10xx.html"
        - "/cf-pages/5xx.html"
        - "/cf-pages/always_online.html"
        - "/cf-pages/blocked.html"
        - "/cf-pages/security_pitstop.html"
        - "/cf-pages/under_attack.html"