name: Continuous Deployment
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout live source
        uses: actions/checkout@v2
        with:
          repository: 'DamianZaremba/damianzaremba.github.io'
          ref: 'main'
          token: '${{ secrets.GH_TOKEN }}'
          path: '_live'

      - name: Install system dependancies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            git wget graphviz \
            openjdk-8-jre python \
            gcc g++ make libgsl-dev \
            ruby-dev ruby-gsl ruby-ffi
          sudo gem install bundler

      - name: Install bundle dependancies
        run: |
          # For some reason gsl fails under bundle
          sudo gem install gsl
          sudo bundle install

      - name: Update external data
        run: make update
        if: github.ref == 'refs/heads/main'

      - name: Transpile site
        run: make stage

      - name: Commit site
        run: make deploy
        if: github.ref == 'refs/heads/main'
